version: '2.4'

services:
  qemu-appimage:
    container_name: qemu-appimage
    build:
      context: .
      dockerfile: ./Dockerfile
      target: full
    volumes:
      - ./input:/input
      - ./output:/output
