ARG BASE_IMAGE=library/ubuntu:focal

FROM docker.io/${BASE_IMAGE}

ENV QEMU_VER=8.0.2

RUN \
  apt-get update && \
  env DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  wget imagemagick file build-essential && \
  apt-get install -y --no-install-recommends \
  bison flex ninja-build valgrind \
  libcap-ng-dev \
  libepoxy-dev \
  libpixman-1-dev \
  libpmem-dev \
  libpulse-dev \
  libsdl2-dev libsdl2-image-dev \
  libslirp-dev \
  libspice-server-dev \
  libusb-1.0-0-dev libusb-dev libusbredirhost-dev \
  libvncserver-dev \
  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /var/lib/apt/lists/*

WORKDIR /opt/qemu

COPY entrypoint.sh /entrypoint.sh

VOLUME /opt/qemu /input /output

ENTRYPOINT ["/entrypoint.sh"]
