name: Publish Docker Image

on:
  schedule:
    - cron: '40 9 * * *'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.git*'
      - 'docker-compose.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '.git*'
      - 'docker-compose.yml'
  workflow_dispatch:

env:
  IMAGE_BASE: library/ubuntu:focal
  REPO_NAME: ${{ github.event.repository.name }}
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:

  variables:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.split.outputs.image_name }}
    steps:
      - name: Set name of image
        id: split
        run: echo "image_name=${REPO_NAME#*-}" >> $GITHUB_OUTPUT

  check:
    needs: variables
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ needs.variables.outputs.image_name }}
    outputs:
      image-needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: ${{ env.IMAGE_BASE }}
          image: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        if: github.event_name == 'schedule'

  build:

    needs: [check, variables]

    env:
      IMAGE_NAME: ${{ needs.variables.outputs.image_name }}

    if: |
      github.event_name != 'schedule' ||
      needs.check.outputs.image-needs-updating == 'true'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        custom_tag: [slim, full]
        include:
          - custom_tag: slim
            is_latest: false
          - custom_tag: full
            is_latest: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Docker Hub registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.base.name=docker.io/${{ env.IMAGE_BASE }}
          tags: |
            type=raw,value=${{ matrix.custom_tag }}

      - name: Extract Docker latest tag
        if: |
          github.event_name != 'pull_request' && matrix.is_latest == true
        id: meta_latest
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest

      - name: Extract Docker PR tag
        if: github.event_name == 'pull_request'
        id: meta_pr
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=ref,suffix=-${{ matrix.custom_tag }},event=pr

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: |
            ./Dockerfile.${{ matrix.custom_tag }}
          build-args: |
            BASE_IMAGE=${{ env.IMAGE_BASE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.meta_latest.outputs.tags }}
            ${{ steps.meta_pr.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
